[Wip][PoC] Add localization in api
code4romania/de-urgenta-backend pull request #147
Opened 2021-10-13 18:19 UTC by idormenco

closes #101

2021-10-14 06:35 UTC, idormenco commented
before merging it we need to fix #82

2021-10-15 09:18 UTC, decembrya requested changes

2021-10-15 09:18 UTC, decembrya commented on Src/DeUrgenta.I18n.Service/Providers/I18NProvider.cs
> +// ReSharper disable SpecifyStringComparison
Please remove this

2021-10-15 09:18 UTC, decembrya commented on Src/DeUrgenta.Domain.I18n/Migrations/I18nDbContextModelSnapshot.cs
> +#pragma warning disable 612, 618
Please remove pragmas, change rules in editorconfig if needed

2021-10-15 10:55 UTC, decembrya approved these changes

2021-10-15 12:24 UTC, merged