Feature/add identity server
code4romania/de-urgenta-backend pull request #15
Opened 2021-04-02 08:34 UTC by idormenco

### What does it fix?

Closes #XXX 

### How has it been tested?

2021-04-02 09:18 UTC, trupci requested changes

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/appsettings.json
> +            "Name": "answersApi",
cleanup

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/appsettings.json
> +        {
cleanup this list: maybe just keep the swagger client for now?

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/appsettings.json
> +    "AdminFromName": "Echipa Jurnal Medical",
rename

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/appsettings.json
> +        "https://prod.stamacasa.ro/register-complete"
cleanup

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/Resources/stateEntityTemplate.html
> +﻿<!doctype html>
remove this file

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/Resources/resetPasswordTemplate.html
> +<html>
We should review this template.

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/Resources/dailyAssessmentTemplate.html
> +﻿<!doctype html>
remove file

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/Resources/dailyAssessmentTemplate.html
> +<html>
remove file

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/Resources/accountConfirmationTemplate.html
> +﻿<!doctype html>
review content for this template

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailTemplate.cs
> +        DailyAssessment,
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailTemplate.cs
> +        StateEntity,
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailConstants.cs
> +            { EmailTemplate.DailyAssessment, "Un minut pe zi pentru o viață liniștită. Chestionar zilnic de evaluare"},
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailConstants.cs
> +            { EmailTemplate.StateEntity, "Rezultate evaluare persoane autoizolare"},
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailConstants.cs
> +            { EmailTemplate.DailyAssessment, "dailyAssessmentTemplate.html"},
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Services/Emailing/EmailConstants.cs
> +            { EmailTemplate.StateEntity, "stateEntityTemplate.html"},
```suggestion
```

2021-04-02 09:18 UTC, trupci commented on Src/DeUrgenta.IdentityServer/Areas/Identity/Pages/Account/Register.cshtml
> +                                Declar că am citit și sunt de acord cu <a href="https://jurnalmedical.ro/termeni-si-conditii">Termenii și Condițiile</a> aplicației Jurnal Medical.
review link

2021-04-02 09:19 UTC, trupci commented on Src/DeUrgenta.IdentityServer/appsettings.json
> +            "Name": "answersApi",
and configure scopes for the new apis

2021-04-02 09:38 UTC, Puiu requested changes
what @trupci said :)

2021-04-03 10:58 UTC, catileptic approved these changes

2021-04-03 10:58 UTC, merged