added throttling for register method to prevent batch e-mail checks +…
code4romania/de-urgenta-backend pull request #154
Opened 2021-10-18 20:05 UTC by Alexei000

… return http error status code on already existing e-mail

### What does it fix?
Closes #61 

This tries to allow the API to inform the client(s) that an e-mail is already used, but prevent a malicious actor from checking many e-mail addresses. This is done by using IP rate-limiting via AspNetCoreRateLimit library.  

However, I am not sure about returning a Conflict response for existing e-mails. The alternative would be returning OK, but this requires a breaking change for the response payload model since now it is just a string.

### How has it been tested?

Currently, I have performed only some manual checks and it works as expected.

- hardcoded IP rating limits in appsettings.json
- not checked how current clients react to a non-OK (non 200) status code
- no automatic tests (I guess I need for #76 to be closed).

2021-10-19 08:09 UTC, idormenco requested changes

2021-10-19 08:09 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +                //TODO: consider returning a 200 with a more complex object as indicated here
please return an ActionResponse object

2021-10-19 08:09 UTC, idormenco commented on Src/DeUrgenta.Api/Startup.cs
> +        private void ConfigureRateLimit(IServiceCollection services)
extract to an extension method

2021-10-19 11:50 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +                //TODO: consider returning a 200 with a more complex object as indicated here
also please decorate this method swagger tags that it can return Status Code: 429 and an example if it is possible

2021-10-19 18:02 UTC, Alexei000 commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +                //TODO: consider returning a 200 with a more complex object as indicated here
Returned `ActionResponse`s for non-OK status responses.
Decorated the method with return metadata + examples.
Moved `ActionResponse` as it seems generic enough to be reused across APIs.

2021-10-19 18:02 UTC, Alexei000 commented on Src/DeUrgenta.Api/Startup.cs
> +        private void ConfigureRateLimit(IServiceCollection services)
done

2021-10-20 07:58 UTC, idormenco commented on Src/DeUrgenta.User.Api/DeUrgenta.User.Api.csproj
> +	  <Folder Include="Models\DTOs\Responses\" />
delete folder `Models\DTOs\Responses`

2021-10-20 07:58 UTC, idormenco commented on Src/DeUrgenta.Api/Startup.cs
> +        {
can you please keep original formating for this method

2021-10-20 16:43 UTC, Alexei000 commented on Src/DeUrgenta.User.Api/DeUrgenta.User.Api.csproj
> +	  <Folder Include="Models\DTOs\Responses\" />
done

2021-10-20 16:44 UTC, Alexei000 commented on Src/DeUrgenta.Api/Startup.cs
> +        {
sorry, I think Resharper tried to be smart. I have reverted the change.

2021-10-21 10:03 UTC, idormenco approved these changes
lgtm

2021-10-28 12:52 UTC, merged