Feature/change password
code4romania/de-urgenta-backend pull request #75
Opened 2021-08-01 00:45 UTC by DSVDavid

### What does it fix?

Implementents an endpoints for changing/resetting user passwords.
I

Closes #65   

This PR adds endpoints for changing an user's password, both for authenticated and non authenticated users (that might have forgotten their password).

There are three new endpoints:

/user/change-password - for changing a signed in user's password
/auth/request-reset-password - for requesting a password reset for users that have forgotten their passwords (takes the user's email address)
/auth/reset-password - for resetting the password of the latter users using the log in

### How has it been tested?

It has been tested using Postman.
Note: I had problems using the SMTP email service so I tested by sending the callback url as a response inside the request-reset-password call. 

I tested the change-password endpoint for the cases the user is not logged in and the confirmation password doesn't match. 
The later also applies for the reset-password endpoint, where I also tested for the case the reset token is invalid. 
Note: For the request-reset-password, the non-existing emails return an OK response for preventing user enumeration.

2021-08-03 11:19 UTC, idormenco commented
Hi @DSVDavid ,
thanks a lot for contributing!
I will review it later today.
Cheers !

2021-08-03 11:56 UTC, DSVDavid commented
Hi @idormenco,
thank you! 
This would be my first PR, so there might be some inaccuracies. But I hope it is ok.
Looking forward for your review.
Cheers!

2021-08-04 09:07 UTC, idormenco requested changes
From functional point of view it works but needs a little bit of work to meet our code style and standards.

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.Api/wwwroot/resetPassword.html
> +            } else {
I think we should handle 400 and display errors from API in a nice way. This can be implemented later in a separate issue. @catileptic what do you think ?

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +
please format this file ,we have an .editorconfig file you might need an extension for that. I guess you are using vscode [this ](https://www.strathweb.com/2019/07/editorconfig-support-in-omnisharp-and-c-extension-vs-code/) might help

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +
remove empty lines

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/UserController.cs
>      {
format this file

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Models/DTOs/Requests/UserChangePassword.cs
> +    public class UserChangePassword
Rename to `UserChangePasswordRequest`

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +                return Ok();
change to `NoContent`

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Controller/AuthController.cs
> +            return Ok(resetUrl);
we should remove `Ok(resetUrl);` and use `NoContent`.
Someone ill intended could enumerate our users using something like:
- call  `request-reset-password` with an random email
* if response is empty there is no such user registered
* if response is with reset url there is such user registered
We should make sure that from an attacker point of view all responses (user exists or not) look the same.

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Models/DTOs/Requests/UserResetPassword.cs
> +    public class UserResetPassword
rename to `UserResetPasswordRequest`

2021-08-04 09:07 UTC, idormenco commented on Src/DeUrgenta.User.Api/Models/DTOs/Requests/UserChangePassword.cs
> +    public class UserChangePassword
we started to use FluentValidation for our requests. Can you use that approach if not we could do it in a different PR

2021-08-04 10:26 UTC, DSVDavid commented
> From functional point of view it works but needs a little bit of work to meet our code style and standards.

@idormenco thank you for your feedback.
I will fix those issues later today.

2021-08-04 10:41 UTC, idormenco commented
Thanks a lot @DSVDavid . Take your time there is no hurry.
I hope my comments are not too picky.

2021-08-04 11:49 UTC, DSVDavid commented
> Thanks a lot @DSVDavid . Take your time there is no hurry.
> I hope my comments are not too picky.

@idormenco Not at all. Better do things right than half right. 
Cheers!

2021-08-07 15:35 UTC, idormenco approved these changes

2021-08-07 15:35 UTC, merged